= OAuth Shield Plugin for ElasticSearch 2.3.2

== Run it simple

Run ES with this plugin installed.
... then run integration tests

[source,sh]
----
mvn -Dskip.integ.tests=false -DskipTests pre-integration-test
----

Default user is `admin-user` with password : `changeme` (see ant file `integration-tests.xml`).
To connect to the instance :

[source,sh]
----
curl -v --user admin_user:changeme -XGET 'localhost:9400/_cluster/settings' | jq '.'
----


== Configure the plugin

[source,yaml]
----
shield:
  audit.enabled: true
  authc:
    realms:
      your-oauth-realm-name:
        order: 0
        type: oauth
        files.role_mapping: config/shield/oauth_role_mapping.yml
        idp:
          connection-timeout-in-millis: 10000 # optional connection tiemout, defaults to 10s
          read-timeout-in-millis: 10000       # optional read response timeout, defaults to 10s
          write-timeout-in-millis: 10000      # optional write request timeout, defaults to 10s
          max-idle-connections: 200           # optional max number of connections, defaults to 200 connections
          proxy:
            host: xxx       # optional
            port: xxx       # mandatory if host is declared
            username: xxx   # optional if host is declared
            password: xxx   # mandatory if username is declared

        token-info:
          url: https:/authority/path/to/tokeninfo # mandatory token-info url
          field:
            user: "user_id"          # mandatory user id field name in token json payload
            scope: "scope"           # mandatory scope field name in token json payload
            expires-in: "expires_in" # mandatory expiration field name in token json payload
            expires-in.unit: SECONDS # optional time unit of expiration (values from java.time.temporal.ChronoUnit)
          cache:
            max-size : 20000         # optional max cache size, defaults to 20000 entries
            expire-in-seconds : 300  # optional cache entry expiration, defaults to 5min
----



== Debug the plugin

These steps indicate how to install a debug agent on the ES instance started by ant.
It uses the variable `tests.jvm.argline` defined in the parent _ant_ script
(see `target/dev-tools/ant/integration-tests.xml` at line 169), this variable is only set
in the `debug` profile declared in this `pom.xml`.


1. In your IDE -- IntelliJ IDEA, let's be serous there -- create a remote debug
   configuration in listen mode, on port 5005

2. Start the debug configuration in your IDE

3. Start Elasticsearch _ant_ task via maven (with the `debug` profile to set `tests.jvm.argline`) :

       mvn -Pdebug -Dskip.integ.tests=false -DskipTests pre-integration-test

4. Then debug, for example with breakpoint here
    `OAuthRealmPlugin.onModule(org.elasticsearch.shield.authc.AuthenticationModule)`
    that is only executed at the ES startup

5. To kill ES just run :

      kill $(jps | grep Elasticsearch | cut -f 1 -d ' ')


== Run integration tests

[source,sh]
----
mvn integration-test
----

== Packages the plugin

[source,sh]
----
mvn package
----

The plugin zip file will be located in `target/release/plugin.zip`, e.g. `target/release/shield-oauth-realm-0.4-SNAPSHOT-shield_2.3.2.zip`

== TODO

- [x] Cache tokens
- [x] Reload mapping
- [x] Investigate `RefreshListener`
- [x] Dependency Injection / avoid it because ES 5 drops guice
- [x] Automate testing
- [x] Logging, via shield configuration
- [x] Configurable token info field to lookup
- [x] truststore, company internal certificate authority => Not necessary
      (Removed usage of Shield's own `ClientSSLService` because it doesn't allow multiple additional trust manager)
- [x] ES 2.3
- [ ] Remove maven warning due to variable usage in project version

== Information

This plugin is loosely based on the example provided https://github.com/elastic/shield-custom-realm-example/tree/2.3[here].

