= OAuth Shield Plugin for ElasticSearch 2.3.4

== Run it simple

Run ES with this plugin installed.
... then run integration tests

[source,sh]
----
mvn -Dskip.integ.tests=false -DskipTests pre-integration-test
----

Default user is `admin-user` with password : `changeme` (see ant file `integration-tests.xml`).
To connect to the instance :

[source,sh]
----
curl -v --user admin_user:changeme -XGET 'localhost:9400/_cluster/settings' | jq '.'
----


== Configure the plugin

[source,yaml]
----
shield:
  audit.enabled: true
  authc:
    realms:
      oauth1:
        order: 0
        type: oauth
        files.role_mapping: config/shield/oauth_role_mapping.yml
        idp:
          connection-timeout-in-millis: 10000
          read-timeout-in-millis: 10000
          write-timeout-in-millis: 10000
          max-idle-connections: 200

        token-info:
          url: https://idp.company.io/nidp/oauth/nam/token
          user.field: user_id
          scope.field: scope
          expires-in.field: expires_in
          expires-in.field.unit: SECONDS
          cache:
            max-size : 20000
            expire-in-seconds : 300
----



== Debug the plugin

These steps indicate how to install a debug agent on the ES instance started by ant.
It uses the variable `tests.jvm.argline` defined in the parent _ant_ script
(see `target/dev-tools/ant/integration-tests.xml` at line 169), this variable is only set
in the `debug` profile declared in this `pom.xml`.


1. In your IDE -- IntelliJ IDEA, let's be serous there -- create a remote debug
   configuration in listen mode, on port 5005

2. Start the debug configuration in your IDE

3. Start Elasticsearch _ant_ task via maven (with the `debug` profile to set `tests.jvm.argline`) :

       mvn -Pdebug -Dskip.integ.tests=false -DskipTests pre-integration-test

4. Then debug, for example with breakpoint here
    `OAuthRealmPlugin.onModule(org.elasticsearch.shield.authc.AuthenticationModule)`
    that is only executed at the ES startup



To kill ES just run :

[source,sh]
----
kill $(jps | grep Elasticsearch | cut -f 1 -d ' ')
----

== TODO

- [x] Cache tokens
- [x] Reload mapping
- [x] Investigate `RefreshListener`
- [x] Dependency Injection / avoid it because ES 5 drops guice
- [ ] Automate testing
- [x] Logging, via shield configuration
- [x] Configurable token info field to lookup
- [ ] truststore, company internal certificate authority
      (Removed usage of Shield's own `ClientSSLService` because it doesn't allow multiple additional trust manager)
- [x] ES 2.3
